project:
  type: website
  output-dir: ../docs

website:
  title: "Saga"
  navbar:
    left:
      - icon: github
        href: https://github.com/spulick/saga_notebooks_quarto
  sidebar: 
    style: "docked"
    search: true
  page-navigation: true
format:
  html:
    theme: 
      light: litera
      dark: sketchy
    css: styles.css
    page-layout: full


